### ISSUE TITLE
Failure when parsing bad legacy server responses

### ISSUE THREAD

**Issue by mrcbax** [kiwiyou/craftping#1]
Here is the error:
```
thread panicked at 'byte index 22 is out of bounds of ``', library/core/src/str/mod.rs:107:9
```
Interesting to note it is ALWAYS byte index 22.

Here are a couple of "servers" that cause this error:

```
163.18.74.14:25565
163.18.74.140:25565
163.18.74.146:25565
163.18.74.147:25565
163.18.74.149:25565
```

**Comment by kiwiyou** [comment]
I tested each server with `examples/servers.rs`, and got only broken pipe errors. And with other server list ping softwares, I found them offline. Could you post other opened servers or, if you own any of them, open the posted server?

**Comment by cleonyc** [comment]
Here are some more that I found. I find that sometimes it produces the error and other times it doesn't. Might be worth trying a few times to reproduce. The irregularity might just be a bug w/ my implementation though.   
```
5.9.116.190:25566
95.217.65.179:25565
95.217.84.241:25565
65.108.110.43:25565
157.90.119.170:25565
78.46.145.151:25565
116.202.224.38:25565
```

**Comment by kiwiyou** [comment]
@cleonyc Sorry for late response. I tested all servers except the first (which refused connection) multiple times and got all ok.

**Comment by NotNite** [comment]
I'm running into this error too - culprit is `101.67.57.177`. Any ideas?

For now blacklisting IPs that I run into with this. `entity.rs:54` seems to be the issue with the slice.

**Comment by kiwiyou** [comment]
@NotNite I tried `101.67.57.177` with `examples/servers.rs`. `version` is parsed as "N/A" but no panic. Could you check what version of craftping you're using?

**Comment by kiwiyou** [comment]
Despite not reproduced, `entity.rs:54` is very likely to be the problem. Returning Error::UnsupportedProtocol on invalid index access may be a solution, but to comprehensively support available servers, more investigation is required.
It's noticeable that the author said "legacy server", and `entity.rs:54` is for the latest server.

**Comment by NotNite** [comment]
I believe I should be using the latest version on Crates - I'll do more testing tomorrow. Might have also just been the wrong IP :P
