### ISSUE TITLE
Question: Why are there 4 0xff betwen the packet id and the protocol version

### ISSUE THREAD

**Issue by kybe236** [kiwiyou/craftping#14]
On this site: https://wiki.vg/Server_List_Ping
It states that after the packet ID 0x00, the protocol version should follow 0x0f.
Why are there 4 0xff between those?
I could not find any resources about those 4 0xff

**Comment by kiwiyou** [comment]
-1 is in VarInt `0xff 0xff 0xff 0xff 0x0f`, not `0x0f`.I see the misleading newline. Maybe will fix.
