### ISSUE TITLE
`Response` should implement Clone

### ISSUE THREAD

**Issue by cleonyc** [kiwiyou/craftping#2]
Hi!

`craftping::entity::Response` should implement the clone trait. I don't think there's any practical reason why it shouldn't, and it would allow much easier handling of responses. Currently I'm working around this by implementing my own custom type and converting the Response to that type. 

I appreciate you taking the time to read this!

Thanks,
Cleo (she/her)

**Comment by kiwiyou** [comment]
Fixed at 0.3.1, thanks!
