### ISSUE TITLE
Response as a raw json string

### ISSUE THREAD

**Issue by Cabbasca** [kiwiyou/craftping#6]
add a .raw thing that gives you the raw json string that the response packet returns

**Comment by kiwiyou** [comment]
Not very hard to implement, but would you give some context in which `raw()` is required?
(If you want a json from server as-is, it requires the `Response` to add a new field (either `pub` or not `pub`), which leads to a breaking change.)

**Comment by Cabbasca** [comment]
not necessarily required but it would be useful when pinging specific servers that have specific responses

**Comment by kiwiyou** [comment]
Added on commit f7ebff4075860977542d9d33f85a0cacdc6cf6aa .
