### ISSUE TITLE
Error: UnsupportedProtocol

### ISSUE THREAD

**Issue by Dalkson** [kiwiyou/craftping#7]
example stalls, then ends with "Error: UnsupportedProtocol" when using it on a specific host. The server is online.
![image](https://user-images.githubusercontent.com/26678089/226437144-bb817eb2-b044-4e3e-8948-66b54bb8888a.png)

A near Identical server does work however.
![image](https://user-images.githubusercontent.com/26678089/226437629-a4c591a9-24c5-42cc-8776-c846dc3ace9a.png)

**Comment by kiwiyou** [comment]
It was because the type of `fmlNetworkVersion` was string, not integer. Thank you for the issue.
