### ISSUE TITLE
panicked at 'attempt to shift left with overflow'

### ISSUE THREAD

**Issue by vrtgs** [kiwiyou/craftping#9]
read_varint can panic at 'attempt to shift left with overflow'

**Comment by kiwiyou** [comment]
Could you give me some contexts, i.e. in what situation does/did the panic occur?

**Comment by vrtgs** [comment]
I don't know but my API panics sometimes when pinged about a server, here is the stacktrace that lead me to read_varint being the issue
`thread 'main' panicked at 'attempt to shift left with overflow', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\craftping-0.4.0\src\tokio.rs:88:19
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
   2: core::panicking::panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:114
   3: craftping::tokio::read_varint::async_fn$0<tokio::net::tcp::stream::TcpStream>
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\craftping-0.4.0\src\tokio.rs:88
   4: craftping::tokio::ping_latest::async_fn$0<tokio::net::tcp::stream::TcpStream>
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\craftping-0.4.0\src\tokio.rs:51
   5: craftping::tokio::ping::async_fn$0<tokio::net::tcp::stream::TcpStream>
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\craftping-0.4.0\src\tokio.rs:37
   6: slp_api::construct_server_list::async_fn$0::closure$0::async_block$0
             at .\src\main.rs:43
   7: futures_util::stream::futures_unordered::impl$7::poll_next<enum2$<slp_api::construct_server_list::async_fn$0::closure$0::async_block_env$0> >
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.28\src\stream\futures_unordered\mod.rs:518
   8: futures_util::stream::stream::StreamExt::poll_next_unpin<futures_util::stream::futures_unordered::FuturesUnordered<enum2$<slp_api::construct_server_list::async_fn$0::closure$0::async_block_env$0> > >
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.28\src\stream\stream\mod.rs:1632
   9: futures_util::stream::stream::buffer_unordered::impl$2::poll_next<futures_util::stream::stream::map::Map<futures_util::stream::iter::Iter<alloc::vec::into_iter::IntoIter<alloc::string::String,alloc::alloc::Global> >,slp_api::construct_server_list
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.28\src\stream\stream\buffer_unordered.rs:75
  10: futures_util::stream::stream::filter_map::impl$3::poll_next<futures_util::stream::stream::buffer_unordered::BufferUnordered<futures_util::stream::stream::map::Map<futures_util::stream::iter::Iter<alloc::vec::into_iter::IntoIter<alloc::string::String,alloc
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.28\src\stream\stream\filter_map.rs:79
  11: futures_util::stream::stream::collect::impl$2::poll<futures_util::stream::stream::filter_map::FilterMap<futures_util::stream::stream::buffer_unordered::BufferUnordered<futures_util::stream::stream::map::Map<futures_util::stream::iter::Iter<alloc::vec::int
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.28\src\stream\stream\collect.rs:50
  12: slp_api::construct_server_list::async_fn$0
             at .\src\main.rs:53
  13: slp_api::main::async_block$0
             at .\src\main.rs:63`
